"""STAGE-0 triage: TIMSS 2019 Grade 8 USA (single-session assessment).

TIMSS is a single-occasion achievement test: there is no repeated
practice, no per-student opportunity count, and no learning-curve signal
to compute. Growth statistics ((c)/(d) in the triage spec) are
STRUCTURALLY N/A here -- not merely unavailable, but nonsensical for a
one-shot assessment -- and are recorded as such rather than computed.

No KC/skill crosswalk is available locally for these items either (only
a coarse Math/Science domain prefix baked into the item id, e.g. "M..."
vs "S..."), so KC-pair decoupling and pure-anchor coverage ((e)/(f) in
the spec) are also structurally N/A and recorded as such.

What IS computed, from the already-extracted local files
(data/timss/timss_g8_usa_poly_*.csv -- read-only inputs, produced
earlier by data/timss/_build_timss_gpcm.R from the raw .sav, NOT
regenerated by this script) is the item/score-category structure: for
each of the genuinely polytomous (0/1/2, partial-credit) constructed-
response items, the response-category distribution and an item-level
"mean score proportion" (mean score / max score) -- the polytomous
analogue of a p-value / correct rate, playing the role of (a)/(b) in the
triage spec. The already-fit classical GPCM discrimination parameters
(timss_g8_usa_gpcm_coef.csv) are reported alongside as bonus context
since the file is already sitting there and trivially readable.

Usage:
    python triage_timss.py <path/to/data/timss> [--out-dir kt-mirt/_planning/triage]
"""
from __future__ import annotations

import argparse
import sys
import time
from collections import Counter
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
from triage_common import (  # noqa: E402
    SATURATION_THRESHOLD,
    category_distribution,
    fraction_above,
    quartiles,
    write_json,
)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("timss_dir")
    parser.add_argument("--out-dir", default=None)
    args = parser.parse_args()

    out_dir = Path(args.out_dir) if args.out_dir else Path(__file__).resolve().parents[2] / "_planning" / "triage"
    out_dir.mkdir(parents=True, exist_ok=True)
    timss_dir = Path(args.timss_dir)

    t0 = time.time()
    triplets_path = timss_dir / "timss_g8_usa_poly_triplets.csv"
    matrix_path = timss_dir / "timss_g8_usa_poly_matrix.csv"
    gpcm_path = timss_dir / "timss_g8_usa_gpcm_coef.csv"

    triplets = pd.read_csv(triplets_path)  # columns: student, item (0-based ints), resp (0/1/2)
    triplets["resp"] = triplets["resp"].astype(int)

    # Recover item names (poly_matrix.csv column order matches the triplets' 0-based item index).
    header_cols = list(pd.read_csv(matrix_path, nrows=0).columns)[1:]  # drop the row-label column
    item_names = {i: name for i, name in enumerate(header_cols)}
    triplets["item_name"] = triplets["item"].map(item_names)

    n_students = int(triplets["student"].nunique())
    n_items = int(triplets["item"].nunique())
    max_score = int(triplets["resp"].max())

    overall_cat_dist = category_distribution(Counter(triplets["resp"].tolist()))
    overall_mean_prop = float(triplets["resp"].mean() / max_score)

    item_stats = triplets.groupby("item_name")["resp"].agg(["size", "mean"])
    item_stats["mean_score_proportion"] = item_stats["mean"] / max_score
    resp_per_student = triplets.groupby("student").size()

    domain = {name: ("math" if name.startswith("M") else "science" if name.startswith("S") else "other")
              for name in item_stats.index}
    n_math = sum(1 for v in domain.values() if v == "math")
    n_science = sum(1 for v in domain.values() if v == "science")

    gpcm_block = None
    if gpcm_path.exists():
        gpcm = pd.read_csv(gpcm_path, index_col=0)
        gpcm_block = {
            "n_items_fit": int(len(gpcm)),
            "discrimination_a_quartiles": quartiles(gpcm["a"]),
            "note": "classical GPCM (mirt, MML) already fit by data/timss/_build_timss_gpcm.R; "
                    "reported as-is, not refit here.",
        }

    results = {
        "bed": "timss_g8_usa",
        "source_files": {
            "triplets": str(triplets_path.resolve()),
            "matrix": str(matrix_path.resolve()),
            "gpcm_coef": str(gpcm_path.resolve()) if gpcm_path.exists() else None,
        },
        "sampling": "none (full local extract used; extract itself is already a minresp>=5 filtered "
                    "subset of the raw .sav, per data/timss/_build_timss_gpcm.R)",
        "design": "single-session assessment (TIMSS 2019 G8 USA achievement booklet); each student "
                  "answers one rotated booklet, one occasion. Item set here is the 31-item genuinely "
                  "polytomous (0/1/2 partial-credit) constructed-response subset identified by "
                  "_classify_items.R, not the full item pool (which also includes dichotomous MC/CR items).",
        "n_students": n_students,
        "n_items": n_items,
        "max_score_per_item": max_score,
        "a_b_item_score_category_structure": {
            "overall_response_category_distribution": overall_cat_dist,
            "overall_mean_score_proportion": overall_mean_prop,
            "per_item_mean_score_proportion_quartiles": quartiles(item_stats["mean_score_proportion"]),
            "frac_items_above_0.85_mean_score_proportion": fraction_above(
                item_stats["mean_score_proportion"], SATURATION_THRESHOLD),
            "responses_per_item_quartiles": quartiles(item_stats["size"]),
            "responses_per_student_quartiles": quartiles(resp_per_student),
            "domain_split_bonus": {
                "note": "coarse M/S item-id prefix only, NOT a fine-grained KC crosswalk",
                "n_math_items": n_math, "n_science_items": n_science,
            },
        },
        "c_d_growth_signal": {
            "status": "structurally N/A",
            "reason": "TIMSS is a single-occasion assessment: no repeated practice, no opportunity "
                      "index, no learning-curve to compute. Not attempted.",
        },
        "e_f_g_decoupling_and_anchors": {
            "status": "structurally N/A",
            "reason": "No item-to-KC crosswalk is available locally for these items (only the coarse "
                      "Math/Science domain prefix on the item id, reported above as a bonus, not a "
                      "skill-level Q-matrix). KC-pair decoupling, pure-anchor coverage, and item-KC "
                      "arity all require such a crosswalk and are not computed.",
        },
        "gpcm_bonus": gpcm_block,
        "runtime_sec": round(time.time() - t0, 1),
    }
    out_path = out_dir / "timss_g8_usa_stats.json"
    write_json(out_path, results)


if __name__ == "__main__":
    main()
